// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Sven Erik Matzen" file="GlobalSuppressions.cs">
//   Copyright (c) Sven Erik Matzen. GNU Library General Public License (LGPL) Version 2.1.
// </copyright>
// <summary>
//   Defines the suppressions for CodeAnalysis
// </summary>
// --------------------------------------------------------------------------------------------------------------------

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.IRuleExecuter.#GetValueType()")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Bouncer.#ForCheckData`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Bouncer.#ForExecution`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Bouncer.#ForMessages`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Bouncer.#GetAfterInvokeActions()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.CheckData`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`1<!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.CheckData`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`1<!0>>,System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Attributes.MethodRuleAttribute>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.CheckData`1.#ForCheckData`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.ConditionalExecution`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`1<!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.ConditionalExecution`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`1<!0>>,System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Attributes.MethodRuleAttribute>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.ConditionalExecution`1.#ForExecution`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.MessageCollector`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`1<!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.MessageCollector`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`1<!0>>,System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Attributes.MethodRuleAttribute>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.MessageCollector`1.#ForMessages`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.RuleExecuter`2.#.ctor(System.Linq.Expressions.Expression`1<System.Func`1<!0>>,System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Attributes.MethodRuleAttribute>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.RuleExecuter`2.#Assert(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Rules.RuleBase`2<!0,System.Object>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.RuleExecuters.RuleExecuter`2.#Assert`1(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Rules.RuleBase`2<!0,!!0>>,!!0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Rules.RuleCollection`2.#GetRuleList()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Rules.RegisteredRules.#GetRulesForType`2()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Rules.RegisteredRules.#RegisterRuleSet`2(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Rules.RuleBase`2<!!0,!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Sem.GenericHelpers.Contracts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Sem.GenericHelpers.Contracts.Exceptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Sem.GenericHelpers.Contracts.Attributes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Rules.RegisteredRules.#RegisterCollection`2(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Contracts.Rules.RuleBase`2<!!0,!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Sem.GenericHelpers.Contracts.Configuration.BouncerConfiguration.#Rules")]
