//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.GenericHelpers.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sem.GenericHelpers.Contracts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validator {0} did throw an exception..
        /// </summary>
        internal static string ConfigurationValidatorBaseRuleStandardMessage {
            get {
                return ResourceManager.GetString("ConfigurationValidatorBaseRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of a rule validation must not be null..
        /// </summary>
        internal static string ErrorMessageForRuleResultIsNull {
            get {
                return ResourceManager.GetString("ErrorMessageForRuleResultIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter does not implement TInterface or is null..
        /// </summary>
        internal static string ImplementsInterfaceRuleStandardMessage {
            get {
                return ResourceManager.GetString("ImplementsInterfaceRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be greater than &gt;&gt;{0}&lt;&lt;..
        /// </summary>
        internal static string IntegerGreaterThanRuleStandardMessage {
            get {
                return ResourceManager.GetString("IntegerGreaterThanRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be lower than &gt;&gt;{0}&lt;&lt;..
        /// </summary>
        internal static string IntegerLowerThanRuleStandardMessage {
            get {
                return ResourceManager.GetString("IntegerLowerThanRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is NULL..
        /// </summary>
        internal static string IsNotNullRuleStandardMessage {
            get {
                return ResourceManager.GetString("IsNotNullRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value is not one of the expected values.
        /// </summary>
        internal static string IsNotOneOfRuleStandardMessage {
            get {
                return ResourceManager.GetString("IsNotOneOfRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is NOT NULL..
        /// </summary>
        internal static string IsNullRuleStandardMessage {
            get {
                return ResourceManager.GetString("IsNullRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value is not one of the expected values.
        /// </summary>
        internal static string IsOneOfRuleStandardMessage {
            get {
                return ResourceManager.GetString("IsOneOfRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is NULL..
        /// </summary>
        internal static string ObjectNotNullRuleStandardMessage {
            get {
                return ResourceManager.GetString("ObjectNotNullRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the parameter..
        /// </summary>
        internal static string RuleBaseInformationStandardMessage {
            get {
                return ResourceManager.GetString("RuleBaseInformationStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule {0} did fail for value name &gt;&gt;{1}&lt;&lt;: {2}.
        /// </summary>
        internal static string RuleValidationResultStandardMessage {
            get {
                return ResourceManager.GetString("RuleValidationResultStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string does not have the maximum length of &gt;&gt;{0}&lt;&lt;..
        /// </summary>
        internal static string StringMaxLengthRuleStandardMessage {
            get {
                return ResourceManager.GetString("StringMaxLengthRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string does not have the minimum length of &gt;&gt;{0}&lt;&lt;..
        /// </summary>
        internal static string StringMinLengthRuleStandardMessage {
            get {
                return ResourceManager.GetString("StringMinLengthRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is null or empty..
        /// </summary>
        internal static string StringNotNullOrEmptyRuleStandardMessage {
            get {
                return ResourceManager.GetString("StringNotNullOrEmptyRuleStandardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string does not match the regular expression &gt;&gt;{0}&lt;&lt;..
        /// </summary>
        internal static string StringRegexMatchRuleStandardMessage {
            get {
                return ResourceManager.GetString("StringRegexMatchRuleStandardMessage", resourceCulture);
            }
        }
    }
}
